# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'


trigger:
  - main
pool:
  name: self-hosted
  #vmImage: ubuntu-latest
steps:
  - powershell: |
      cd C:\Users\Dan\projects\vuln_node_express
      $Env:PATH = "C:\Program Files\Docker\Docker\resources\bin;$Env:PATH"
      docker run --rm --publish 3000:3000 --detach --name nodeexpressvulny stackhawk/nodeexpressvulny
  - task: HawkScanInstall@1
    inputs:
      version: latest
  - task: RunHawkScan@1
    inputs:
      configFile: "stackhawk.yml"
      version: "latest"
    env:
      HAWK_API_KEY: $(hawk_api_key)