# .github/workflows/build-and-test.yml
name: HawkScan
on:
  push: 
    branches:
      - main
  pull_request:
jobs:
  build-and-test:
    name: Build and Scan
    runs-on: ubuntu-20.04
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Daemonize our Node API service
        run: npm run start &
      - name: Env Dump
        run: env
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2.0.0
        continue-on-error: true
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
